* Passage

Passage [1] provides correct and complete results for SPARQL queries, despite 
time quotas enforced by public SPARQL endpoints. Contrarily to state-of-the-art
approaches [2, 3], Passage works solely within SPARQL boundaries: a query execution
returns correct (possibly partial) results along with a SPARQL continuation query; 
executing the continuation query provides missing results, itself with another SPARQL 
continuation query; until termination.

** Installation

#+BEGIN_SRC shell :async :session clone-passage :results none
  git clone https://github.com/Chat-Wane/passage.git
  cd passage
#+END_SRC

#+BEGIN_SRC shell :async :session build-passage :results none
  mvn clean package
#+END_SRC

** Usage

- =passage-server.jar= provides a server running passage/raw/blazegraph as a SPARQL endpoint, it requires a few changes to the [[https://github.com/Chat-Wane/passage-secret/blob/main/passage-cli/src/main/resources/exampleConfig.ttl][configuration file]]. =--help= for more information.
- =passage.jar= provides a one time execution without server. =--help= for more information.
- =raw.jar= provides a one time execution of a online sample-based query execution. =--help= for more information.

- [[https://github.com/passage-org/passage-comunica][passage-comunica]] provides a client to automate the continuation loop.

  
** Datasets

Passage relies on a [[https://github.com/blazegraph][Blazegraph storage]]. To ingest your RDF data,
please follow [[https://github.com/blazegraph/database/wiki/Quick_Start][their instructions]]. Alternatively, we provide a few
datasets already ingested for trials:

- [[https://zenodo.org/records/14224920][FedShop200]] for federations of SPARQL endpoints;
- [[https://zenodo.org/records/12744414][WatDiv]] for an e-commerce dataset;
- WDBench [[https://zenodo.org/records/12510935][(Part A)]] [[https://zenodo.org/records/12511050][(Part B)]] for a sample of Wikidata.

** References

[1] T.H.T. Pham, G. Montoya, B. Nédelec, H. Skaf-Molli, and P. Molli. [[https://hal.science/hal-05055927v1/file/rfp2567.pdf][Passage: Ensuring Completeness and Responsiveness of Public SPARQL Endpoints with SPARQL Continuation Queries]]. WWW '25: Proceedings of the ACM on Web Conference 2025.

[2] T. Minier, H. Skaf-Molli and P. Molli. /SaGe: Web Preemption for Public SPARQL Query services/.
    In Proceedings of the World Wide Web Conference (2019).

[3] R. Verborgh, M. Vander Sande, O. Hartig, J. Van Herwegen, L. De Vocht, B. De Meester,  G. Haesendonck and P. Colpaert. /Triple Pattern Fragments: A Low-Cost Knowledge Graph Interface for the Web/.
    In Journal of Web Semantics (2016).
