package fr.gdd.passage.volcano.executions;

import fr.gdd.passage.blazegraph.BlazegraphBackend;
import fr.gdd.passage.blazegraph.datasets.BlazegraphInMemoryDatasetsFactory;
import fr.gdd.passage.commons.utils.MultisetResultChecking;
import fr.gdd.passage.volcano.ExecutorUtils;
import fr.gdd.passage.volcano.PassageExecutionContextBuilder;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.MethodSource;
import org.openrdf.query.MalformedQueryException;
import org.openrdf.query.QueryEvaluationException;
import org.openrdf.repository.RepositoryException;
import org.openrdf.sail.SailException;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

@Disabled("Should be reworked.")
@Deprecated
public class CountTest {

    private final static Logger log = LoggerFactory.getLogger(CountTest.class);

    @ParameterizedTest
    @MethodSource("fr.gdd.passage.volcano.InstanceProviderForTests#pullProvider")
    public void simple_count_on_a_single_triple_pattern(PassageExecutionContextBuilder<?,?> builder) throws RepositoryException, SailException {
        final BlazegraphBackend blazegraph = new BlazegraphBackend(BlazegraphInMemoryDatasetsFactory.triples9());
        builder.setBackend(blazegraph);
        String query = "SELECT (COUNT(*) AS ?count) { ?p <http://address> ?c }";

        var results = ExecutorUtils.execute(query, builder);
        assertEquals(1, results.size()); // ?count = 3
        assertTrue(MultisetResultChecking.containsResult(results, List.of("count"),
                List.of("3")));
        blazegraph.close();
    }

    @ParameterizedTest
    @MethodSource("fr.gdd.passage.volcano.InstanceProviderForTests#pullProvider")
    public void count_of_tp_but_stops_inside_the_operator_focusing_on_last_step (PassageExecutionContextBuilder<?,?> builder) throws RepositoryException, SailException {
        final BlazegraphBackend blazegraph = new BlazegraphBackend(BlazegraphInMemoryDatasetsFactory.triples9());
        builder.setBackend(blazegraph);
        // this query is generated by a pause, should work flawlessly though.
        String queryAsString = """
        SELECT  (( count(*) + 2 ) AS ?count) WHERE {
            SELECT * WHERE { ?p  <http://address>  ?c } OFFSET  2 }
        """;

        var results = ExecutorUtils.execute(queryAsString, builder);
        assertEquals(1, results.size()); // 1 result where ?count = 3
        assertTrue(MultisetResultChecking.containsResult(results, List.of("count"), List.of("3")));
        blazegraph.close();
    }

    @ParameterizedTest
    @MethodSource("fr.gdd.passage.volcano.InstanceProviderForTests#pullProvider")
    public void count_of_something_that_does_not_exist_is_zero(PassageExecutionContextBuilder<?,?> builder) throws RepositoryException, QueryEvaluationException, MalformedQueryException, SailException {
        final BlazegraphBackend blazegraph = new BlazegraphBackend(BlazegraphInMemoryDatasetsFactory.triples9());
        builder.setBackend(blazegraph);
        String query = "SELECT (COUNT(*) AS ?count) { ?p <http://does_not_exist> ?c }";

        var expected = blazegraph.executeQuery(query);
        log.debug("Expected: {}", expected);

        var results = ExecutorUtils.execute(query, builder);
        assertEquals(1, results.size()); // not even a ?count = 0
        assertTrue(MultisetResultChecking.containsResult(results,
                List.of("count"),
                List.of("0")));
        blazegraph.close();
    }

    @ParameterizedTest
    @MethodSource("fr.gdd.passage.volcano.InstanceProviderForTests#pullProvider")
    public void variable_undefined_in_subquery (PassageExecutionContextBuilder<?,?> builder) throws RepositoryException, QueryEvaluationException, MalformedQueryException, SailException {
        final BlazegraphBackend blazegraph = new BlazegraphBackend(BlazegraphInMemoryDatasetsFactory.triples9());
        builder.setBackend(blazegraph);
        String query = "SELECT (COUNT(?undefined) AS ?count) { ?p <http://address> ?c }";

        var expected = blazegraph.executeQuery(query);
        log.debug("Expected: {}", expected);

        var results = ExecutorUtils.execute(query, builder);
        assertEquals(1, results.size());
        assertTrue(MultisetResultChecking.containsResult(results, List.of("count"), List.of("0")));
        blazegraph.close();
    }

    @ParameterizedTest
    @MethodSource("fr.gdd.passage.volcano.InstanceProviderForTests#pullProvider")
    public void count_in_bgp_without_results (PassageExecutionContextBuilder<?,?> builder) throws RepositoryException, QueryEvaluationException, MalformedQueryException, SailException {
        final BlazegraphBackend blazegraph = new BlazegraphBackend(BlazegraphInMemoryDatasetsFactory.triples9());
        builder.setBackend(blazegraph);
        String query = """
            SELECT (COUNT(*) AS ?count) {
                VALUES ?c { <http://washington> }
                ?p <http://address> ?c.
            }""";

        var expected = blazegraph.executeQuery(query);
        log.debug("Expected: {}", expected);

        var results = ExecutorUtils.execute(query, builder);
        assertEquals(1, results.size());
        assertTrue(MultisetResultChecking.containsResult(results, List.of("count"), List.of("0")));
        blazegraph.close();
    }

    @ParameterizedTest
    @MethodSource("fr.gdd.passage.volcano.InstanceProviderForTests#pullProvider")
    public void count_on_bgp_should_pause_in_bgp_without_providing_result (PassageExecutionContextBuilder<?,?> builder) throws RepositoryException, SailException {
        final BlazegraphBackend blazegraph = new BlazegraphBackend(BlazegraphInMemoryDatasetsFactory.triples9());
        builder.setBackend(blazegraph);
        String queryAsString = """
            SELECT (COUNT(*) AS ?count) {
                ?p <http://address> ?c .
                ?p <http://own> ?a
            }""";

        var results = ExecutorUtils.execute(queryAsString, builder);
        assertEquals(1, results.size()); // 1 result where ?count = 3
        assertTrue(MultisetResultChecking.containsResult(results, List.of("count"), List.of("3")));
        blazegraph.close();
    }

    @ParameterizedTest
    @MethodSource("fr.gdd.passage.volcano.InstanceProviderForTests#pullProvider")
    public void count_on_a_specific_variable_but_still_tp (PassageExecutionContextBuilder<?,?> builder) throws RepositoryException, QueryEvaluationException, MalformedQueryException, SailException {
        final BlazegraphBackend blazegraph = new BlazegraphBackend(BlazegraphInMemoryDatasetsFactory.triples9());
        builder.setBackend(blazegraph);
        String query = "SELECT (COUNT(?p) AS ?count) { ?p <http://address> ?c }";

        var expected = blazegraph.executeQuery(query);
        log.debug("Expected: {}", expected);

        var results = ExecutorUtils.execute(query, builder);
        assertEquals(1, results.size()); // ?count = 3
        assertTrue(MultisetResultChecking.containsResult(results, List.of("count"),
                List.of("3")));
        blazegraph.close();
    }

    @ParameterizedTest
    @MethodSource("fr.gdd.passage.volcano.InstanceProviderForTests#pullProvider")
    public void count_in_optional_so_everything_does_not_count (PassageExecutionContextBuilder<?,?> builder) throws RepositoryException, QueryEvaluationException, MalformedQueryException, SailException {
        final BlazegraphBackend blazegraph = new BlazegraphBackend(BlazegraphInMemoryDatasetsFactory.triples9());
        builder.setBackend(blazegraph);
        String query = """
            SELECT (COUNT(?a) AS ?count) {
                ?p <http://address> ?c
                OPTIONAL { ?p <http://own> ?a }}""";

        var expected = blazegraph.executeQuery(query);
        log.debug("Expected: {}", expected);

        var results = ExecutorUtils.execute(query, builder);
        assertEquals(1, results.size()); // ?count = 3
        assertTrue(MultisetResultChecking.containsResult(results, List.of("count"),
                List.of("3"))); // if count=5, it means that the iterator wrongfully counted Bob and Carol…
        blazegraph.close();
    }

    @ParameterizedTest
    @MethodSource("fr.gdd.passage.volcano.InstanceProviderForTests#pullProvider")
    public void a_tp_join_with_a_count_subquery (PassageExecutionContextBuilder<?,?> builder) throws RepositoryException, QueryEvaluationException, MalformedQueryException, SailException {
        // The sub-query does not project `p`, so it should probably be a carthesian
        // product, unless the variable `p` is projected in the sub-query. However,
        // it requires a `GROUP BY`, which is then difficult to implement for continuations.
        final BlazegraphBackend blazegraph = new BlazegraphBackend(BlazegraphInMemoryDatasetsFactory.triples9());
        builder.setBackend(blazegraph);
        String query = """
            SELECT * WHERE {
                ?p <http://address> ?c .
                {SELECT (COUNT(*) AS ?count) { ?p <http://own> ?animal }}
            }""";

        var expected = blazegraph.executeQuery(query);
        log.debug("Expected: {}", expected);
        // Alice, Bob, and Carol all have a count of 3 because the sub-query is executed as is.

        var results = ExecutorUtils.execute(query, builder);
        assertEquals(3, results.size());
        assertTrue(MultisetResultChecking.containsAllResults(results, List.of("p", "count"),
                List.of("Alice", "3"), List.of("Bob", "3"), List.of("Carol", "3")));
        blazegraph.close();
    }

    @ParameterizedTest
    @MethodSource("fr.gdd.passage.volcano.InstanceProviderForTests#pullProvider")
    public void count_with_bound_variables_projected_this_time_by_the_count (PassageExecutionContextBuilder<?,?> builder) throws RepositoryException, QueryEvaluationException, MalformedQueryException, SailException {
        final BlazegraphBackend blazegraph = new BlazegraphBackend(BlazegraphInMemoryDatasetsFactory.triples9());
        builder.setBackend(blazegraph);
        String query = """
            SELECT * WHERE {
                ?p <http://address> ?c .
                {SELECT ?p (COUNT(*) AS ?count) { ?p <http://own> ?animal } GROUP BY ?p}
            }""";

        var expected = blazegraph.executeQuery(query);
        log.debug("Expected: {}", expected);
        // Only Alice is returned, with a value of 3 since only it matches in the sub-query.

        var results = ExecutorUtils.execute(query, builder);
        assertEquals(1, results.size()); // ?count = 3 for Alice; Bob and Carol don't even exist.
        assertTrue(MultisetResultChecking.containsResult(results, List.of("p", "count"), List.of("Alice", "3")));
        blazegraph.close();
    }

    @ParameterizedTest
    @MethodSource("fr.gdd.passage.volcano.InstanceProviderForTests#pullProvider")
    public void count_with_group_by_at_the_top (PassageExecutionContextBuilder<?,?> builder) throws RepositoryException, QueryEvaluationException, MalformedQueryException, SailException {
        // For now, it throws because GROUP BY needs DISTINCT on keys when they are not bounded by the environment.
        final BlazegraphBackend blazegraph = new BlazegraphBackend(BlazegraphInMemoryDatasetsFactory.triples9());
        builder.setBackend(blazegraph);
        String query = """
                SELECT ?p (COUNT(*) AS ?nbAnimals) WHERE {
                    ?p <http://address> ?c .
                    ?p <http://own> ?animal
                } GROUP BY ?p""";

        var expected = blazegraph.executeQuery(query);
        log.debug("Expected: {}", expected);

        assertThrows(UnsupportedOperationException.class, () -> ExecutorUtils.execute(query, builder));
        blazegraph.close();
    }

    @Disabled("Not implemented yet when multiple COUNTs in a single (sub-)query.")
    @ParameterizedTest
    @MethodSource("fr.gdd.passage.volcano.InstanceProviderForTests#pullProvider")
    public void multiple_counts_in_a_single_aggregate (PassageExecutionContextBuilder<?,?> builder) throws RepositoryException, QueryEvaluationException, MalformedQueryException, SailException {
        final BlazegraphBackend blazegraph = new BlazegraphBackend(BlazegraphInMemoryDatasetsFactory.triples9());
        builder.setBackend(blazegraph);
        String query = """
            SELECT (COUNT(?p) AS ?pCount) (COUNT(?animal) AS ?aCount) WHERE {
                ?p <http://own> ?animal
            }""";

        var expected = blazegraph.executeQuery(query);
        log.debug("Expected: {}", expected);

        var results = ExecutorUtils.execute(query, builder);
        assertEquals(1, results.size());
        assertTrue(MultisetResultChecking.containsResult(results,
                List.of("pCount", "aCount"),
                List.of("3", "3"))); // both 3 since they count the same
        blazegraph.close();
    }

    @Disabled("Not implemented yet when multiple COUNTs in a single (sub-)query.")
    @ParameterizedTest
    @MethodSource("fr.gdd.passage.volcano.InstanceProviderForTests#pullProvider")
    public void multiple_counts_in_a_single_aggregate_with_optional (PassageExecutionContextBuilder<?,?> builder) throws RepositoryException, QueryEvaluationException, MalformedQueryException, SailException {
        final BlazegraphBackend blazegraph = new BlazegraphBackend(BlazegraphInMemoryDatasetsFactory.triples9());
        builder.setBackend(blazegraph);
        String query = """
            SELECT (COUNT(?p) AS ?pCount) (COUNT(?a) AS ?aCount) WHERE {
                ?p <http://address> ?c
                OPTIONAL { ?p <http://own> ?a }
            }""";

        var expected = blazegraph.executeQuery(query);
        log.debug("Expected: {}", expected);

        var results = ExecutorUtils.execute(query, builder);
        assertEquals(1, results.size());
        assertTrue(MultisetResultChecking.containsResult(results,
                List.of("pCount", "aCount"),
                List.of("5", "3"))); // p: 3 Alices + Bob + Carol; a: dog + cat + snake
        blazegraph.close();
    }



//    @Disabled("Trial to see what group byies look like.")
//    @Test
//    public void meow() throws RepositoryException, QueryEvaluationException, MalformedQueryException {
//        final BlazegraphBackend blazegraph = new BlazegraphBackend(IM4Blazegraph.triples9());
//        // TODO obtain identical result to this?
//        String queryAsString = """
//        SELECT * WHERE {
//            ?p <http://address> ?address .
//            {SELECT (COUNT(*) AS ?count) ?p { ?p <http://own> ?animal } GROUP BY ?p }
//        }
//        """;
//
//        //        (join
//        //          (bgp (triple ?p <http://address> ?address))
//        //          (project (?count ?p)
//        //              (extend ((?count ?.0))
//        //              (group (?p) ((?.0 (count)))
//        //                  (bgp (triple ?p <http://own> ?animal))))))
//
//        Op meow = Algebra.compile(QueryFactory.create(queryAsString));
//
//        ExecutionContext ec = new ExecutionContext(DatasetFactory.empty().asDatasetGraph());
//        ec.getContext().set(BackendConstants.BACKEND, blazegraph);
//
//        var results = blazegraph.executeQuery(queryAsString);
//        log.debug(results.toString());
//    }
}
